### PR TITLE
Clean up thanks to CI

### PR DESCRIPTION
**Pull request by Thovi98**
@ericgaspar, I just deleted my repository to make this one as the main one.

I don’t see the setting to let me add the "issues" section, could you please add it?
And as I’m not part of the Yunohost-Orgarization, I won’t be able to !testme I suppose? Do you agree that I ping you whenever I need it? :) 

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
An invitation has been sent

**Comment by Thovi98** [comment]
Thank you!

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
!testme

**Pull request merged**
